export enum EnvironmentVariable {
  CPU_LIMIT_MILLICORES = "CPU_LIMIT_MILLICORES",
  GCP_PROJECT_ID = "GCP_PROJECT_ID",
  GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS",
  NODE_OPTIONS = "NODE_OPTIONS",
  NPM_PACKAGE_VERSION = "npm_package_version",
  RESOURCE_DETECTORS = "OTEL_NODE_RESOURCE_DETECTORS",
  TRACES_SAMPLER = "OTEL_TRACES_SAMPLER",
  TRACES_SAMPLER_ARG = "OTEL_TRACES_SAMPLER_ARG",
}
