export enum InstrumentationName {
  AMQPLIB = "@opentelemetry/instrumentation-amqplib",
  AWS_SDK = "@opentelemetry/instrumentation-aws-sdk",
  CONNECT = "@opentelemetry/instrumentation-connect",
  DNS = "@opentelemetry/instrumentation-dns",
  EXPRESS = "@opentelemetry/instrumentation-express",
  FASTIFY = "@opentelemetry/instrumentation-fastify",
  FS = "@opentelemetry/instrumentation-fs",
  GRAPHQL = "@opentelemetry/instrumentation-graphql",
  GRPC = "@opentelemetry/instrumentation-grpc",
  HTTP = "@opentelemetry/instrumentation-http",
  IOREDIS = "@opentelemetry/instrumentation-ioredis",
  KAFKAJS = "@opentelemetry/instrumentation-kafkajs",
  KNEX = "@opentelemetry/instrumentation-knex",
  MONGODB = "@opentelemetry/instrumentation-mongodb",
  MONGOOSE = "@opentelemetry/instrumentation-mongoose",
  MYSQL2 = "@opentelemetry/instrumentation-mysql2",
  NESTJS_CORE = "@opentelemetry/instrumentation-nestjs-core",
  NET = "@opentelemetry/instrumentation-net",
  PG = "@opentelemetry/instrumentation-pg",
  PINO = "@opentelemetry/instrumentation-pino",
  REDIS = "@opentelemetry/instrumentation-redis",
  RUNTIME_NODE = "@opentelemetry/instrumentation-runtime-node",
  UNDICI = "@opentelemetry/instrumentation-undici",
  WINSTON = "@opentelemetry/instrumentation-winston",
}
