export enum OtlpEnvironmentVariable {
  METRICS_ENDPOINT = "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT",
  METRICS_EXPORTER = "OTEL_METRICS_EXPORTER",
  TRACES_ENDPOINT = "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
}
