export enum TelemetryErrorCode {
  MISSING_SERVICE_NAME = "MISSING_SERVICE_NAME",
  INVALID_SAMPLE_RATIO = "INVALID_SAMPLE_RATIO",
  INVALID_DOC_TRACE_RATIO = "INVALID_DOC_TRACE_RATIO",
  UNSUPPORTED_EXPORTER = "UNSUPPORTED_EXPORTER",
  UNSUPPORTED_PROPAGATOR = "UNSUPPORTED_PROPAGATOR",
  UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL",
  MISSING_OPTIONAL_DEPENDENCY = "MISSING_OPTIONAL_DEPENDENCY",
}
